@echo off
echo Starting Backend Server...
cd backend
echo Installing dependencies...
pip install fastapi uvicorn python-multipart aiofiles
echo Starting server...
python -m uvicorn main:app --host 127.0.0.1 --port 8000 --reload
pause